# Generated by Django 3.2 on 2021-06-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameAccum', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('Status', models.BooleanField()),
                ('NameTran', models.CharField(max_length=30)),
                ('Tranlong', models.FloatField()),
                ('Tranlat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('Status', models.BooleanField()),
                ('idAccumulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.accumulation')),
            ],
        ),
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLine', models.CharField(max_length=30)),
                ('beginLongitude', models.FloatField()),
                ('beginLatitude', models.FloatField()),
                ('endLongitude', models.FloatField()),
                ('endLatitude', models.FloatField()),
                ('nameCabinet', models.CharField(max_length=30)),
                ('placeCabinet', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('idAccumulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.accumulation')),
                ('idCabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.cabinet')),
                ('idCentral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.central')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pylon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('idLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.line')),
            ],
        ),
        migrations.AddField(
            model_name='central',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.region'),
        ),
    ]
